language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.9-linux64.tar.xz
  - tar xf arduino-1.6.9-linux64.tar.xz
  - sudo mv arduino-1.6.9 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - sudo ln -s /usr/local/share/arduino/arduino-builder /usr/local/bin/arduino-builder
script:
  - cat $PWD/victoria/victoria.ino >> $PWD/victoria/build.ino 
  - cat $PWD/victoria/victoria.ino >> $PWD/victoria/buildtests.ino 
  - cat $PWD/victoria/run.ino >> $PWD/victoria/build.ino 
  - cat $PWD/victoria/test.ino >> $PWD/victoria/buildtests.ino 
  - arduino-builder -hardware /usr/local/share/arduino/hardware -tools /usr/local/share/arduino/hardware/tools/avr -tools /usr/local/share/arduino/tools-builder -libraries /usr/local/share/arduino/libraries -libraries $PWD/libraries/ -fqbn arduino:avr:mega:cpu=atmega2560 $PWD/victoria/build.ino
  - arduino-builder -hardware /usr/local/share/arduino/hardware -tools /usr/local/share/arduino/hardware/tools/avr -tools /usr/local/share/arduino/tools-builder -libraries /usr/local/share/arduino/libraries -libraries $PWD/libraries/ -fqbn arduino:avr:mega:cpu=atmega2560 $PWD/victoria/buildtests.ino